before_install:
 - sudo apt-get install autoconf
 -  sudo apt-get install libtool
 - wget http://download.zeromq.org/zeromq-4.0.3.tar.gz
 -  tar -xvzf zeromq-4.0.3.tar.gz
 - cd zeromq-4.0.3/
 - ./configure
 - sudo make install
 - go get github.com/pebbe/zmq4
 - go get github.com/syndtr/goleveldb/leveldb

script: 
 - cd ..
 - make
 
language: go

go:
 - 1.1
 - tip
