all:
	rm -rf /home/nilang/Documents/go-space/go/src/github.com/nilangshah/Raft/log*	
	go install github.com/nilangshah/Raft
	go install github.com/nilangshah/Raft/testlog
	testlog
	rm -rf /home/nilang/Documents/go-space/go/src/github.com/nilangshah/Raft/Raftlog*

